name: CI

on:
  pull_request: 
    branches: 
      - main
  push: 
    branches: 
      - main
  workflow_dispatch: 

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install BATS locally
        run: npm install --prefix . bats

      - name: Create alias for BATS
        run: echo "alias bats='./node_modules/.bin/bats'" >> $HOME/.bashrc
      
      - name: Run BATS Tests
        run: bats test/test.bats
