name: CI

on:
  pull_request: 
    branches: 
      - main
  push: 
    branches: 
      - main
  workflow_dispatch: 

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js Toolchain
        uses: actions/setup-node@v4
        with:
          node-version: 20.14.0
      
      - name: Install BATS
        run: npm install bats

      - name: Run BATS Tests
        run: bats test/test.bats
