name: CI

on:
  pull_request: 
    branches: 
      - main
  push: 
    branches: 
      - main
  workflow_dispatch: 

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install BATS
        run: npm install bats

      - name: Add npm package binary directory to PATH
        run: echo 'export PATH="./node_modules/.bin:$PATH"' >> $GITHUB_ENV

      - name: Run BATS Tests
        run: bats test/test.bats
